version: '3.7'

services:

  pontevirtuale:
    container_name: pontevirtuale
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '127.0.0.1:4200:4200'
    restart: unless-stopped

